name: Indian_Monsoon_Onset
channels:
  - conda-forge
  - defaults
dependencies:
# Python
  - python
# Code Linter
  - pylint
# Code Formatter
  - black
# Numerical Operations
  - numpy
  - scipy
  - openblas
# Database I/O
  - pandas
  - netCDF4
  - h5py
  - xarray
# Image processing
  - matplotlib
  - ffmpeg
  - openh264
  - cartopy
  - plotly
# Interactive UI
  - jupyter
  - ipykernel
# NCL
  - conda-forge::ncl